#!/bin/bash

echo "═══════════════════════════════════════════════════════════"
echo "🔧 PROCÉDURE COMPLÈTE POUR CORRIGER LE DÉCALAGE HORAIRE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "⚠️  IMPORTANT: Cette procédure DOIT être suivie dans l'ordre!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "ÉTAPE 1: REBUILD ET REDÉMARRAGE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Les changements dans config/database.js nécessitent un rebuild:"
echo ""
echo "  docker-compose down"
echo "  docker-compose build --no-cache notes-app"
echo "  docker-compose up -d"
echo ""
echo "Attendez que le serveur soit complètement démarré:"
echo ""
echo "  docker-compose logs -f notes-app"
echo ""
echo "Attendez de voir: '✓ Serveur NoteFlow démarré sur le port 2222'"
echo "Puis appuyez sur Ctrl+C"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "ÉTAPE 2: SUPPRESSION DES ÉVÉNEMENTS EXISTANTS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Les événements synchronisés AVANT le fix doivent être supprimés:"
echo ""
echo "  docker exec noteflow-postgres psql -U noteflow -d noteflow -p 5499 -c \"DELETE FROM calendar_events\""
echo ""
echo "Résultat attendu: DELETE X (où X = nombre d'événements)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "ÉTAPE 3: RESYNCHRONISATION GOOGLE CALENDAR"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Ouvrez http://localhost:2222"
echo "2. Connectez-vous"
echo "3. Allez dans 'Admin' → 'Google Calendar'"
echo "4. Cliquez sur '🔄 Synchroniser'"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "ÉTAPE 4: VÉRIFICATION"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "L'événement 'Dr Julian Wlodarczak' devrait maintenant afficher:"
echo ""
echo "  Google Calendar: 10:20"
echo "  NoteFlow:        10:20 ✅ (et non plus 11:20)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Si le problème persiste après ces étapes, lancez le diagnostic:"
echo ""
echo "  docker exec notes-todo-app node scripts/debug-sync.js"
echo ""
echo "═══════════════════════════════════════════════════════════"
